name: Push to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Push to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 13.51.242.132
          username: ubuntu
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          port: 22
          script: |
            export PATH="/usr/bin:$PATH"
            export NVM_DIR="$HOME/.nvm"
            source $NVM_DIR/nvm.sh

            echo "Node version: $(node -v)"
            echo "NPM version: $(npm -v)"
            echo "private key $(${{ secrets.PRIVATE_SSH_KEY }})"

            cd ~/bms
            git pull origin main
            pnpm install
            pnpm run build
            pm2 restart all